In [58]:
import pandas as pd
import numpy as np

df = pd.read_csv('retail_sales.csv', encoding='latin')
df

   TransactionID   Date CustomerID     Product  Quantity  Price  TotalAmount
0        TID0001  45029   CUST0006   product B        -2  32.88   -72.727928
1        TID0002  45275        NaN   product A         8  32.88   263.040000
2        TID0003  45197   CUST0001   product D        10  32.88   328.800000
3        TID0004  45033   CUST0006  product  B         9  32.88   295.920000
4        TID0004  45033   CUST0006  product  B         9  32.88   295.920000
5        TID0005  44998        NaN   product D         2  32.88    65.760000
6        TID0006  45115        NaN   product D         8  32.88   263.040000
7        TID0007  44947   cust0010   product B         2  32.88    65.760000
8        TID0008  45182        NaN   product B        10  32.88   404.097557
9        TID0009  45048   CUST0003   product B         7  32.88   230.160000
10       TID0010  45141   CUST0004   product B        12  32.88   338.716238
11       TID0011  45257   CUST0003   product B         9  32.88          NaN
12       TID0011  45257   CUST0003   product B         9  32.88          NaN
13       TID0012  45014   CUST0007   product D         7  32.88   230.160000
14       TID0013  45026   CUST0007   product B         3  32.88    98.640000
15       TID0014  45286        NaN   product A         9  32.88   295.920000
16       TID0015  45078   CUST0002   product C         7  32.88   230.160000
17       TID0016  45057   CUST0010   product B        -5  32.88  -164.400000
18       TID0017  45076        NaN   product B         1  32.88          NaN
19       TID0018  45235   CUST0007   product D         3  32.88    98.640000
20       TID0019  45184   cust0008   product B        -5  32.88          NaN
21       TID0019  45184   cust0008   product B        -5  32.88          NaN
22       TID0020  45270   TEMP0011   product B         6  32.88   197.280000

In [59]:
#inspect data first
print(df.isnull().sum())

#checking datatype and basic information
print(df.info())

TransactionID    0
Date             0
CustomerID       6
Product          0
Quantity         0
Price            0
TotalAmount      5
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionID  23 non-null     str
 1   Date           23 non-null     int64
 2   CustomerID     17 non-null     str
 3   Product        23 non-null     str
 4   Quantity       23 non-null     int64
 5   Price          23 non-null     float64
 6   TotalAmount    18 non-null     float64
dtypes: float64(2), int64(2), str(3)
memory usage: 1.4 KB
None

In [60]:
#filling missing customer ids with unknown
df["CustomerID"] = df["CustomerID"].fillna("Unknown")

df

   TransactionID   Date CustomerID     Product  Quantity  Price  TotalAmount
0        TID0001  45029   CUST0006   product B        -2  32.88   -72.727928
1        TID0002  45275    Unknown   product A         8  32.88   263.040000
2        TID0003  45197   CUST0001   product D        10  32.88   328.800000
3        TID0004  45033   CUST0006  product  B         9  32.88   295.920000
4        TID0004  45033   CUST0006  product  B         9  32.88   295.920000
5        TID0005  44998    Unknown   product D         2  32.88    65.760000
6        TID0006  45115    Unknown   product D         8  32.88   263.040000
7        TID0007  44947   cust0010   product B         2  32.88    65.760000
8        TID0008  45182    Unknown   product B        10  32.88   404.097557
9        TID0009  45048   CUST0003   product B         7  32.88   230.160000
10       TID0010  45141   CUST0004   product B        12  32.88   338.716238
11       TID0011  45257   CUST0003   product B         9  32.88          NaN
12       TID0011  45257   CUST0003   product B         9  32.88          NaN
13       TID0012  45014   CUST0007   product D         7  32.88   230.160000
14       TID0013  45026   CUST0007   product B         3  32.88    98.640000
15       TID0014  45286    Unknown   product A         9  32.88   295.920000
16       TID0015  45078   CUST0002   product C         7  32.88   230.160000
17       TID0016  45057   CUST0010   product B        -5  32.88  -164.400000
18       TID0017  45076    Unknown   product B         1  32.88          NaN
19       TID0018  45235   CUST0007   product D         3  32.88    98.640000
20       TID0019  45184   cust0008   product B        -5  32.88          NaN
21       TID0019  45184   cust0008   product B        -5  32.88          NaN
22       TID0020  45270   TEMP0011   product B         6  32.88   197.280000

In [61]:
#dropping rows with missing total amount
df = df.dropna(subset=["TotalAmount"])
df

   TransactionID   Date CustomerID     Product  Quantity  Price  TotalAmount
0        TID0001  45029   CUST0006   product B        -2  32.88   -72.727928
1        TID0002  45275    Unknown   product A         8  32.88   263.040000
2        TID0003  45197   CUST0001   product D        10  32.88   328.800000
3        TID0004  45033   CUST0006  product  B         9  32.88   295.920000
4        TID0004  45033   CUST0006  product  B         9  32.88   295.920000
5        TID0005  44998    Unknown   product D         2  32.88    65.760000
6        TID0006  45115    Unknown   product D         8  32.88   263.040000
7        TID0007  44947   cust0010   product B         2  32.88    65.760000
8        TID0008  45182    Unknown   product B        10  32.88   404.097557
9        TID0009  45048   CUST0003   product B         7  32.88   230.160000
10       TID0010  45141   CUST0004   product B        12  32.88   338.716238
13       TID0012  45014   CUST0007   product D         7  32.88   230.160000
14       TID0013  45026   CUST0007   product B         3  32.88    98.640000
15       TID0014  45286    Unknown   product A         9  32.88   295.920000
16       TID0015  45078   CUST0002   product C         7  32.88   230.160000
17       TID0016  45057   CUST0010   product B        -5  32.88  -164.400000
19       TID0018  45235   CUST0007   product D         3  32.88    98.640000
22       TID0020  45270   TEMP0011   product B         6  32.88   197.280000

In [62]:
#checking for duplicate rows
print(df.duplicated().sum())

1

In [63]:
df.duplicated()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
13    False
14    False
15    False
16    False
17    False
19    False
22    False
dtype: bool

In [64]:
#View duplicate rows
print(df[df.duplicated()])

  TransactionID   Date CustomerID     Product  Quantity  Price  TotalAmount
4       TID0004  45033   CUST0006  product  B         9  32.88       295.92

In [65]:
#remove duplicated rows
df = df.drop_duplicates()
df

   TransactionID   Date CustomerID     Product  Quantity  Price  TotalAmount
0        TID0001  45029   CUST0006   product B        -2  32.88   -72.727928
1        TID0002  45275    Unknown   product A         8  32.88   263.040000
2        TID0003  45197   CUST0001   product D        10  32.88   328.800000
3        TID0004  45033   CUST0006  product  B         9  32.88   295.920000
5        TID0005  44998    Unknown   product D         2  32.88    65.760000
6        TID0006  45115    Unknown   product D         8  32.88   263.040000
7        TID0007  44947   cust0010   product B         2  32.88    65.760000
8        TID0008  45182    Unknown   product B        10  32.88   404.097557
9        TID0009  45048   CUST0003   product B         7  32.88   230.160000
10       TID0010  45141   CUST0004   product B        12  32.88   338.716238
13       TID0012  45014   CUST0007   product D         7  32.88   230.160000
14       TID0013  45026   CUST0007   product B         3  32.88    98.640000
15       TID0014  45286    Unknown   product A         9  32.88   295.920000
16       TID0015  45078   CUST0002   product C         7  32.88   230.160000
17       TID0016  45057   CUST0010   product B        -5  32.88  -164.400000
19       TID0018  45235   CUST0007   product D         3  32.88    98.640000
22       TID0020  45270   TEMP0011   product B         6  32.88   197.280000

In [66]:
#Replace negative Quantity values with 0
df.loc[df["Quantity"] < 0, "Quantity"] = 0

#Adjusting TotalAmount accordingly
df["TotalAmount"] = df["Quantity"] * df["Price"]

print(df.head())

  TransactionID   Date CustomerID     Product  Quantity  Price  TotalAmount
0       TID0001  45029   CUST0006   product B         0  32.88         0.00
1       TID0002  45275    Unknown   product A         8  32.88       263.04
2       TID0003  45197   CUST0001   product D        10  32.88       328.80
3       TID0004  45033   CUST0006  product  B         9  32.88       295.92
5       TID0005  44998    Unknown   product D         2  32.88        65.76

In [68]:
#checking data types
print(df.dtypes)

TransactionID        str
Date               int64
CustomerID           str
Product              str
Quantity           int64
Price            float64
TotalAmount      float64
dtype: object

In [69]:
df["Date"] = pd.to_datetime(
    df["Date"],
    origin="1899-12-30",
    unit="D"
)

df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount
0,TID0001,2023-04-13,CUST0006,product B,0,32.88,0.00
1,TID0002,2023-12-15,Unknown,product A,8,32.88,263.04
2,TID0003,2023-09-28,CUST0001,product D,10,32.88,328.80
3,TID0004,2023-04-17,CUST0006,product B,9,32.88,295.92
5,TID0005,2023-03-13,Unknown,product D,2,32.88,65.76
6,TID0006,2023-07-08,Unknown,product D,8,32.88,263.04
7,TID0007,2023-01-21,cust0010,product B,2,32.88,65.76
8,TID0008,2023-09-13,Unknown,product B,10,32.88,328.80
9,TID0009,2023-05-02,CUST0003,product B,7,32.88,230.16
10,TID0010,2023-08-03,CUST0004,product B,12,32.88,394.56
13,TID0012,2023-03-29,CUST0007,product D,7,32.88,230.16
14,TID0013,2023-04-10,CUST0007,product B,3,32.88,98.64
15,TID0014,2023-12-26,Unknown,product A,9,32.88,295.92
16,TID0015,2023-06-01,CUST0002,product C,7,32.88,230.16
17,TID0016,2023-05-11,CUST0010,product B,0,32.88,0.00
19,TID0018,2023-11-05,CUST0007,product D,3,32.88,98.64
22,TID0020,2023-12-10,TEMP0011,product B,6,32.88,197.28

In [70]:
print(df["CustomerID"].dtype)

str

In [71]:
#customerID as a string
df["CustomerID"] = df["CustomerID"].astype(str)
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount
0,TID0001,2023-04-13,CUST0006,product B,0,32.88,0.00
1,TID0002,2023-12-15,Unknown,product A,8,32.88,263.04
2,TID0003,2023-09-28,CUST0001,product D,10,32.88,328.80
3,TID0004,2023-04-17,CUST0006,product B,9,32.88,295.92
5,TID0005,2023-03-13,Unknown,product D,2,32.88,65.76
6,TID0006,2023-07-08,Unknown,product D,8,32.88,263.04
7,TID0007,2023-01-21,cust0010,product B,2,32.88,65.76
8,TID0008,2023-09-13,Unknown,product B,10,32.88,328.80
9,TID0009,2023-05-02,CUST0003,product B,7,32.88,230.16
10,TID0010,2023-08-03,CUST0004,product B,12,32.88,394.56
13,TID0012,2023-03-29,CUST0007,product D,7,32.88,230.16
14,TID0013,2023-04-10,CUST0007,product B,3,32.88,98.64
15,TID0014,2023-12-26,Unknown,product A,9,32.88,295.92
16,TID0015,2023-06-01,CUST0002,product C,7,32.88,230.16
17,TID0016,2023-05-11,CUST0010,product B,0,32.88,0.00
19,TID0018,2023-11-05,CUST0007,product D,3,32.88,98.64
22,TID0020,2023-12-10,TEMP0011,product B,6,32.88,197.28

In [72]:
print(df["CustomerID"].dtype)

str

In [73]:
#Adding new column month
df["Month"] = df["Date"].dt.month
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount,Month
0,TID0001,2023-04-13,CUST0006,product B,0,32.88,0.00,4
1,TID0002,2023-12-15,Unknown,product A,8,32.88,263.04,12
2,TID0003,2023-09-28,CUST0001,product D,10,32.88,328.80,9
3,TID0004,2023-04-17,CUST0006,product B,9,32.88,295.92,4
5,TID0005,2023-03-13,Unknown,product D,2,32.88,65.76,3
6,TID0006,2023-07-08,Unknown,product D,8,32.88,263.04,7
7,TID0007,2023-01-21,cust0010,product B,2,32.88,65.76,1
8,TID0008,2023-09-13,Unknown,product B,10,32.88,328.80,9
9,TID0009,2023-05-02,CUST0003,product B,7,32.88,230.16,5
10,TID0010,2023-08-03,CUST0004,product B,12,32.88,394.56,8
13,TID0012,2023-03-29,CUST0007,product D,7,32.88,230.16,3
14,TID0013,2023-04-10,CUST0007,product B,3,32.88,98.64,4
15,TID0014,2023-12-26,Unknown,product A,9,32.88,295.92,12
16,TID0015,2023-06-01,CUST0002,product C,7,32.88,230.16,6
17,TID0016,2023-05-11,CUST0010,product B,0,32.88,0.00,5
19,TID0018,2023-11-05,CUST0007,product D,3,32.88,98.64,11
22,TID0020,2023-12-10,TEMP0011,product B,6,32.88,197.28,12

In [74]:
#Add a new column RevenueCategory that categorizes transactions based on TotalAmount:
#"Low" for transactions under $50
#"Medium" for transactions between $50 and $200
#"High" for transactions above $200
df["RevenueCategory"] = pd.cut(df["TotalAmount"],
bins=[0, 50, 200, float("inf")],
labels=["Low", "Medium", "High"]
)
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount,Month,RevenueCategory
0,TID0001,2023-04-13,CUST0006,product B,0,32.88,0.00,4,NaN
1,TID0002,2023-12-15,Unknown,product A,8,32.88,263.04,12,High
2,TID0003,2023-09-28,CUST0001,product D,10,32.88,328.80,9,High
3,TID0004,2023-04-17,CUST0006,product B,9,32.88,295.92,4,High
5,TID0005,2023-03-13,Unknown,product D,2,32.88,65.76,3,Medium
6,TID0006,2023-07-08,Unknown,product D,8,32.88,263.04,7,High
7,TID0007,2023-01-21,cust0010,product B,2,32.88,65.76,1,Medium
8,TID0008,2023-09-13,Unknown,product B,10,32.88,328.80,9,High
9,TID0009,2023-05-02,CUST0003,product B,7,32.88,230.16,5,High
10,TID0010,2023-08-03,CUST0004,product B,12,32.88,394.56,8,High
13,TID0012,2023-03-29,CUST0007,product D,7,32.88,230.16,3,High
14,TID0013,2023-04-10,CUST0007,product B,3,32.88,98.64,4,Medium
15,TID0014,2023-12-26,Unknown,product A,9,32.88,295.92,12,High
16,TID0015,2023-06-01,CUST0002,product C,7,32.88,230.16,6,High
17,TID0016,2023-05-11,CUST0010,product B,0,32.88,0.00,5,NaN
19,TID0018,2023-11-05,CUST0007,product D,3,32.88,98.64,11,Medium
22,TID0020,2023-12-10,TEMP0011,product B,6,32.88,197.28,12,Medium

In [75]:
#Filter out transactions where Price or Quantity is 0.
df = df[
    (df["Price"] !=0) & (df["Quantity"] != 0)
    ]
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount,Month,RevenueCategory
1,TID0002,2023-12-15,Unknown,product A,8,32.88,263.04,12,High
2,TID0003,2023-09-28,CUST0001,product D,10,32.88,328.80,9,High
3,TID0004,2023-04-17,CUST0006,product B,9,32.88,295.92,4,High
5,TID0005,2023-03-13,Unknown,product D,2,32.88,65.76,3,Medium
6,TID0006,2023-07-08,Unknown,product D,8,32.88,263.04,7,High
7,TID0007,2023-01-21,cust0010,product B,2,32.88,65.76,1,Medium
8,TID0008,2023-09-13,Unknown,product B,10,32.88,328.80,9,High
9,TID0009,2023-05-02,CUST0003,product B,7,32.88,230.16,5,High
10,TID0010,2023-08-03,CUST0004,product B,12,32.88,394.56,8,High
13,TID0012,2023-03-29,CUST0007,product D,7,32.88,230.16,3,High
14,TID0013,2023-04-10,CUST0007,product B,3,32.88,98.64,4,Medium
15,TID0014,2023-12-26,Unknown,product A,9,32.88,295.92,12,High
16,TID0015,2023-06-01,CUST0002,product C,7,32.88,230.16,6,High
19,TID0018,2023-11-05,CUST0007,product D,3,32.88,98.64,11,Medium
22,TID0020,2023-12-10,TEMP0011,product B,6,32.88,197.28,12,Medium

In [76]:
#Convert all product names to title case (e.g., product a -> Product A).
df["Product"] = df["Product"].str.title()
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount,Month,RevenueCategory
1,TID0002,2023-12-15,Unknown,Product A,8,32.88,263.04,12,High
2,TID0003,2023-09-28,CUST0001,Product D,10,32.88,328.80,9,High
3,TID0004,2023-04-17,CUST0006,Product B,9,32.88,295.92,4,High
5,TID0005,2023-03-13,Unknown,Product D,2,32.88,65.76,3,Medium
6,TID0006,2023-07-08,Unknown,Product D,8,32.88,263.04,7,High
7,TID0007,2023-01-21,cust0010,Product B,2,32.88,65.76,1,Medium
8,TID0008,2023-09-13,Unknown,Product B,10,32.88,328.80,9,High
9,TID0009,2023-05-02,CUST0003,Product B,7,32.88,230.16,5,High
10,TID0010,2023-08-03,CUST0004,Product B,12,32.88,394.56,8,High
13,TID0012,2023-03-29,CUST0007,Product D,7,32.88,230.16,3,High
14,TID0013,2023-04-10,CUST0007,Product B,3,32.88,98.64,4,Medium
15,TID0014,2023-12-26,Unknown,Product A,9,32.88,295.92,12,High
16,TID0015,2023-06-01,CUST0002,Product C,7,32.88,230.16,6,High
19,TID0018,2023-11-05,CUST0007,Product D,3,32.88,98.64,11,Medium
22,TID0020,2023-12-10,TEMP0011,Product B,6,32.88,197.28,12,Medium

In [77]:
#Remove any leading or trailing whitespace from the product names.
df["Product"] = df["Product"].str.strip()
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount,Month,RevenueCategory
1,TID0002,2023-12-15,Unknown,Product A,8,32.88,263.04,12,High
2,TID0003,2023-09-28,CUST0001,Product D,10,32.88,328.80,9,High
3,TID0004,2023-04-17,CUST0006,Product B,9,32.88,295.92,4,High
5,TID0005,2023-03-13,Unknown,Product D,2,32.88,65.76,3,Medium
6,TID0006,2023-07-08,Unknown,Product D,8,32.88,263.04,7,High
7,TID0007,2023-01-21,cust0010,Product B,2,32.88,65.76,1,Medium
8,TID0008,2023-09-13,Unknown,Product B,10,32.88,328.80,9,High
9,TID0009,2023-05-02,CUST0003,Product B,7,32.88,230.16,5,High
10,TID0010,2023-08-03,CUST0004,Product B,12,32.88,394.56,8,High
13,TID0012,2023-03-29,CUST0007,Product D,7,32.88,230.16,3,High
14,TID0013,2023-04-10,CUST0007,Product B,3,32.88,98.64,4,Medium
15,TID0014,2023-12-26,Unknown,Product A,9,32.88,295.92,12,High
16,TID0015,2023-06-01,CUST0002,Product C,7,32.88,230.16,6,High
19,TID0018,2023-11-05,CUST0007,Product D,3,32.88,98.64,11,Medium
22,TID0020,2023-12-10,TEMP0011,Product B,6,32.88,197.28,12,Medium

In [78]:
#Clean up the CustomerID column:
#Ensure that all CustomerID values are in uppercase.
df["CustomerID"] = df["CustomerID"].str.upper()
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount,Month,RevenueCategory
1,TID0002,2023-12-15,UNKNOWN,Product A,8,32.88,263.04,12,High
2,TID0003,2023-09-28,CUST0001,Product D,10,32.88,328.80,9,High
3,TID0004,2023-04-17,CUST0006,Product B,9,32.88,295.92,4,High
5,TID0005,2023-03-13,UNKNOWN,Product D,2,32.88,65.76,3,Medium
6,TID0006,2023-07-08,UNKNOWN,Product D,8,32.88,263.04,7,High
7,TID0007,2023-01-21,CUST0010,Product B,2,32.88,65.76,1,Medium
8,TID0008,2023-09-13,UNKNOWN,Product B,10,32.88,328.80,9,High
9,TID0009,2023-05-02,CUST0003,Product B,7,32.88,230.16,5,High
10,TID0010,2023-08-03,CUST0004,Product B,12,32.88,394.56,8,High
13,TID0012,2023-03-29,CUST0007,Product D,7,32.88,230.16,3,High
14,TID0013,2023-04-10,CUST0007,Product B,3,32.88,98.64,4,Medium
15,TID0014,2023-12-26,UNKNOWN,Product A,9,32.88,295.92,12,High
16,TID0015,2023-06-01,CUST0002,Product C,7,32.88,230.16,6,High
19,TID0018,2023-11-05,CUST0007,Product D,3,32.88,98.64,11,Medium
22,TID0020,2023-12-10,TEMP0011,Product B,6,32.88,197.28,12,Medium

In [79]:
#Remove any leading or trailing whitespace from the CustomerID.
df["CustomerID"] = df["CustomerID"].str.strip()
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount,Month,RevenueCategory
1,TID0002,2023-12-15,UNKNOWN,Product A,8,32.88,263.04,12,High
2,TID0003,2023-09-28,CUST0001,Product D,10,32.88,328.80,9,High
3,TID0004,2023-04-17,CUST0006,Product B,9,32.88,295.92,4,High
5,TID0005,2023-03-13,UNKNOWN,Product D,2,32.88,65.76,3,Medium
6,TID0006,2023-07-08,UNKNOWN,Product D,8,32.88,263.04,7,High
7,TID0007,2023-01-21,CUST0010,Product B,2,32.88,65.76,1,Medium
8,TID0008,2023-09-13,UNKNOWN,Product B,10,32.88,328.80,9,High
9,TID0009,2023-05-02,CUST0003,Product B,7,32.88,230.16,5,High
10,TID0010,2023-08-03,CUST0004,Product B,12,32.88,394.56,8,High
13,TID0012,2023-03-29,CUST0007,Product D,7,32.88,230.16,3,High
14,TID0013,2023-04-10,CUST0007,Product B,3,32.88,98.64,4,Medium
15,TID0014,2023-12-26,UNKNOWN,Product A,9,32.88,295.92,12,High
16,TID0015,2023-06-01,CUST0002,Product C,7,32.88,230.16,6,High
19,TID0018,2023-11-05,CUST0007,Product D,3,32.88,98.64,11,Medium
22,TID0020,2023-12-10,TEMP0011,Product B,6,32.88,197.28,12,Medium

In [83]:
#If a CustomerID starts with the string "TEMP", replace it with "CUST".
df["CustomerID"] = df["CustomerID"].str.replace("TEMP", "CUST")
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount,Month,RevenueCategory
1,TID0002,2023-12-15,UNKNOWN,Product A,8,32.88,263.04,12,High
2,TID0003,2023-09-28,CUST0001,Product D,10,32.88,328.80,9,High
3,TID0004,2023-04-17,CUST0006,Product B,9,32.88,295.92,4,High
5,TID0005,2023-03-13,UNKNOWN,Product D,2,32.88,65.76,3,Medium
6,TID0006,2023-07-08,UNKNOWN,Product D,8,32.88,263.04,7,High
7,TID0007,2023-01-21,CUST0010,Product B,2,32.88,65.76,1,Medium
8,TID0008,2023-09-13,UNKNOWN,Product B,10,32.88,328.80,9,High
9,TID0009,2023-05-02,CUST0003,Product B,7,32.88,230.16,5,High
10,TID0010,2023-08-03,CUST0004,Product B,12,32.88,394.56,8,High
13,TID0012,2023-03-29,CUST0007,Product D,7,32.88,230.16,3,High
14,TID0013,2023-04-10,CUST0007,Product B,3,32.88,98.64,4,Medium
15,TID0014,2023-12-26,UNKNOWN,Product A,9,32.88,295.92,12,High
16,TID0015,2023-06-01,CUST0002,Product C,7,32.88,230.16,6,High
19,TID0018,2023-11-05,CUST0007,Product D,3,32.88,98.64,11,Medium
22,TID0020,2023-12-10,CUST0011,Product B,6,32.88,197.28,12,Medium

In [84]:
#Create a new column ProductCategory that categorizes products based on their names.
#Extract information from the Product column:
#Create a new column ProductCategory that categorizes products based on their names. For example:
#If the product name contains "A" or "B", categorize it as "Category 1".
#If the product name contains "C" or "D", categorize it as "Category 2".

df["ProductCategory"] = df["Product"].apply(
    lambda x: "Category 1"
    if("A" in x or "B" in x)
    else "Category 2"
    if("C" in x or "D" in x)
    else "other"
)
df

,TransactionID,Date,CustomerID,Product,Quantity,Price,TotalAmount,Month,RevenueCategory,ProductCategory
1,TID0002,2023-12-15,UNKNOWN,Product A,8,32.88,263.04,12,High,Category 1
2,TID0003,2023-09-28,CUST0001,Product D,10,32.88,328.80,9,High,Category 2
3,TID0004,2023-04-17,CUST0006,Product B,9,32.88,295.92,4,High,Category 1
5,TID0005,2023-03-13,UNKNOWN,Product D,2,32.88,65.76,3,Medium,Category 2
6,TID0006,2023-07-08,UNKNOWN,Product D,8,32.88,263.04,7,High,Category 2
7,TID0007,2023-01-21,CUST0010,Product B,2,32.88,65.76,1,Medium,Category 1
8,TID0008,2023-09-13,UNKNOWN,Product B,10,32.88,328.80,9,High,Category 1
9,TID0009,2023-05-02,CUST0003,Product B,7,32.88,230.16,5,High,Category 1
10,TID0010,2023-08-03,CUST0004,Product B,12,32.88,394.56,8,High,Category 1
13,TID0012,2023-03-29,CUST0007,Product D,7,32.88,230.16,3,High,Category 2
14,TID0013,2023-04-10,CUST0007,Product B,3,32.88,98.64,4,Medium,Category 1
15,TID0014,2023-12-26,UNKNOWN,Product A,9,32.88,295.92,12,High,Category 1
16,TID0015,2023-06-01,CUST0002,Product C,7,32.88,230.16,6,High,Category 2
19,TID0018,2023-11-05,CUST0007,Product D,3,32.88,98.64,11,Medium,Category 2
22,TID0020,2023-12-10,CUST0011,Product B,6,32.88,197.28,12,Medium,Category 1

In [85]:
#Save the cleaned and prepared dataset to a new file called “cleaned_retail_sales.csv”.
df.to_csv("cleaned_retail -sales.csv", index=False)

#we use index=False tto avoid Pandas from saving row numbers as an extra column, unwanted columns.