In [82]:
import pandas as pd

#create a DataFrame
sales_df = {
    'Date':['04-10-2025', '12-03-2025', '15-06-2024', '04-07-2025'],
    'Store':['Apple_Store', 'Best_Buy', 'Home_Depot', 'Walmart'],
    'Product':['Laptop', 'Phone', 'Office_table', 'Printer'],
    'Quantity':[4, 15, 2, 4],
    'Price':[1000, 500, 800, 200]
}

df = pd.DataFrame(sales_df)
print("\nPandas DataFrame")
print(df)

Pandas DataFrame
         Date        Store       Product  Quantity  Price
0  04-10-2025  Apple_Store        Laptop         4   1000
1  12-03-2025     Best_Buy         Phone        15    500
2  15-06-2024   Home_Depot  Office_table         2    800
3  04-07-2025      Walmart       Printer         4    200

In [83]:
#inspecting the data
df.head()

         Date        Store       Product  Quantity  Price
0  04-10-2025  Apple_Store        Laptop         4   1000
1  12-03-2025     Best_Buy         Phone        15    500
2  15-06-2024   Home_Depot  Office_table         2    800
3  04-07-2025      Walmart       Printer         4    200

In [84]:
df.tail()

         Date        Store       Product  Quantity  Price
0  04-10-2025  Apple_Store        Laptop         4   1000
1  12-03-2025     Best_Buy         Phone        15    500
2  15-06-2024   Home_Depot  Office_table         2    800
3  04-07-2025      Walmart       Printer         4    200

In [85]:
df['Price']

0    1000
1     500
2     800
3     200
Name: Price, dtype: int64

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      4 non-null      str
 1   Store     4 non-null      str
 2   Product   4 non-null      str
 3   Quantity  4 non-null      int64
 4   Price     4 non-null      int64
dtypes: int64(2), str(3)
memory usage: 292.0 bytes

In [87]:
#Getting summary information of the DataFrame
summary = df.describe()
print("\nSummary Information:")
print(summary)

Summary Information:
        Quantity   Price
count   4.000000     4.0
mean    6.250000   625.0
std     5.909033   350.0
min     2.000000   200.0
25%     3.500000   425.0
50%     4.000000   650.0
75%     6.750000   850.0
max    15.000000  1000.0

In [88]:
#include all columns
df.describe(include='all')

              Date        Store Product   Quantity   Price
count            4            4       4   4.000000     4.0
unique           4            4       4        NaN     NaN
top     04-10-2025  Apple_Store  Laptop        NaN     NaN
freq             1            1       1        NaN     NaN
mean           NaN          NaN     NaN   6.250000   625.0
std            NaN          NaN     NaN   5.909033   350.0
min            NaN          NaN     NaN   2.000000   200.0
25%            NaN          NaN     NaN   3.500000   425.0
50%            NaN          NaN     NaN   4.000000   650.0
75%            NaN          NaN     NaN   6.750000   850.0
max            NaN          NaN     NaN  15.000000  1000.0

In [89]:
# Adding a new column to the DataFrame
df['Total_sales'] = df['Quantity'] * df['Price']
print("\nDataFrame after adding a new column:")
df

DataFrame after adding a new column:

         Date        Store       Product  Quantity  Price  Total_sales
0  04-10-2025  Apple_Store        Laptop         4   1000         4000
1  12-03-2025     Best_Buy         Phone        15    500         7500
2  15-06-2024   Home_Depot  Office_table         2    800         1600
3  04-07-2025      Walmart       Printer         4    200          800

In [125]:
# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              4 non-null      datetime64[us]
 1   Store             4 non-null      str
 2   Product           4 non-null      str
 3   Quantity          4 non-null      int64
 4   Price             4 non-null      int64
 5   Total_sales       4 non-null      int64
 6   Total-store_sale  4 non-null      int64
 7   Total_Sales       4 non-null      int64
 8   Discounted Price  4 non-null      float64
 9   Discounted_Price  4 non-null      float64
dtypes: datetime64[us](1), float64(2), int64(5), str(2)
memory usage: 452.0 bytes

In [91]:
#Filter the DataFrame to get all sales that occurred 
# in the month of July.
july_sales = df[df['Date'].dt.month_name() == 'July']
print(july_sales)

#or using month number
july_sale = df[df['Date'].dt.month == 7]
print(july_sale)

        Date    Store  Product  Quantity  Price  Total_sales
3 2025-07-04  Walmart  Printer         4    200          800
        Date    Store  Product  Quantity  Price  Total_sales
3 2025-07-04  Walmart  Printer         4    200          800

In [92]:
#Get all sales where the Quantity sold is greater than 10.
sales_filter = df[df['Quantity'] > 10]

print("\nFiltering data where Quantity > 10:")
print(sales_filter)

Filtering data where Quantity > 10:
        Date     Store Product  Quantity  Price  Total_sales
1 2025-03-12  Best_Buy   Phone        15    500         7500

In [93]:
#Get the unique store names then compute 
# the total sales per store.
unique_store_names = df['Store'].unique()
print(unique_store_names)

<StringArray>
['Apple_Store', 'Best_Buy', 'Home_Depot', 'Walmart']
Length: 4, dtype: str

In [94]:
#compute the total sales per store.
df['Total-store_sale'] = df['Quantity'] * df['Price']
df

,Date,Store,Product,Quantity,Price,Total_sales,Total-store_sale
0,2025-10-04,Apple_Store,Laptop,4,1000,4000,4000
1,2025-03-12,Best_Buy,Phone,15,500,7500,7500
2,2024-06-15,Home_Depot,Office_table,2,800,1600,1600
3,2025-07-04,Walmart,Printer,4,200,800,800

In [95]:
#Get the unique product and calculate 
# the average price of each product.
unique_product = df['Product'].unique()
print(unique_product)

<StringArray>
['Laptop', 'Phone', 'Office_table', 'Printer']
Length: 4, dtype: str

In [96]:
#the average price of each product.
average_product_price = df.groupby('Product')['Price'].mean()
print(average_product_price)

Product
Laptop          1000.0
Office_table     800.0
Phone            500.0
Printer          200.0
Name: Price, dtype: float64

In [97]:
#Sort the DataFrame by Total Sales in descending order.
sorted_df = df.sort_values(by='Total_sales', ascending=False)
print(sorted_df)

        Date        Store       Product  Quantity  Price  Total_sales  \
1 2025-03-12     Best_Buy         Phone        15    500         7500
0 2025-10-04  Apple_Store        Laptop         4   1000         4000
2 2024-06-15   Home_Depot  Office_table         2    800         1600
3 2025-07-04      Walmart       Printer         4    200          800

   Total-store_sale
1              7500
0              4000
2              1600
3               800

In [99]:
#Rank the stores based on Total Sales
df['Total_Sales'] = df['Quantity'] * df['Price']

store_sales = df.groupby('Store')['Total_Sales'].sum().reset_index()

store_sales['Rank'] = store_sales['Total_Sales'].rank(ascending=False,
    method='dense'
)

print(store_sales)

         Store  Total_Sales  Rank
0  Apple_Store         4000   2.0
1     Best_Buy         7500   1.0
2   Home_Depot         1600   3.0
3      Walmart          800   4.0

In [122]:
#Define custom function
#discounted_price = ['Price'] * 0.1
#final_price = ['Price'] - discounted_price
#final_price = Price - (0.1 × Price)
#final_price = Price × (1 - 0.1)
##final_price = Price × 0.9
def discounted_price(row):
    if row['Quantity'] > 5:
       return row['Price'] * 0.9
    return row['Price']
#Apply the custom function to the DataFrame
df['Discounted_Price'] = df.apply(discounted_price, axis=1)
df
print(df)

        Date        Store       Product  Quantity  Price  Total_sales  \
0 2025-10-04  Apple_Store        Laptop         4   1000         4000
1 2025-03-12     Best_Buy         Phone        15    500         7500
2 2024-06-15   Home_Depot  Office_table         2    800         1600
3 2025-07-04      Walmart       Printer         4    200          800

   Total-store_sale  Total_Sales  Discounted Price  Discounted_Price
0              4000         4000            1000.0            1000.0
1              7500         7500             450.0             450.0
2              1600         1600             800.0             800.0
3               800          800             200.0             200.0

In [124]:
#discounted_price = df.apply(discounted_price, axis=1)
#print(discounted_price)

#df['Discounted Price'] = df.apply(discounted_price, axis=1)
df['Discounted Price'] = df.apply(discounted_price, axis=1)
print(df)

        Date        Store       Product  Quantity  Price  Total_sales  \
0 2025-10-04  Apple_Store        Laptop         4   1000         4000
1 2025-03-12     Best_Buy         Phone        15    500         7500
2 2024-06-15   Home_Depot  Office_table         2    800         1600
3 2025-07-04      Walmart       Printer         4    200          800

   Total-store_sale  Total_Sales  Discounted Price  Discounted_Price
0              4000         4000            1000.0            1000.0
1              7500         7500             450.0             450.0
2              1600         1600             800.0             800.0
3               800          800             200.0             200.0