In [2]:
import pandas as pd

# Step 1: Load the datasets
movies_df = pd.read_csv('movies.csv')
ratings_df = pd.read_excel('ratings.xlsx')
#ratings_df
movies_df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [4]:
ratings_df

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [5]:
#inspecting movies dataset
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [6]:
#inspecting ratings dataset
ratings_df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [7]:
#getting columns
print(movies_df.columns)

Index(['movieId', 'title', 'genres'], dtype='str')

In [8]:
print(ratings_df.columns)

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='str')

In [9]:
#merging the movies and ratings 
# DataFrames on the movieId column.
merged_df = pd.merge(movies_df, ratings_df, on='movieId')
merged_df

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [10]:
#or we can also do this
movie_ratings_merge = movies_df.merge(ratings_df, on="movieId")
movie_ratings_merge

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [11]:
#inspecting insights, getting highest rated movie
top_movies = merged_df.groupby("title")["rating"].mean()
print(top_movies.sort_values(ascending=False))

title
Karlson Returns (1970)                                                         5.0
Zeitgeist: Moving Forward (2011)                                               5.0
Dream of Light (a.k.a. Quince Tree Sun, The) (Sol del membrillo, El) (1992)    5.0
Dragons: Gift of the Night Fury (2011)                                         5.0
12 Angry Men (1997)                                                            5.0
                                                                              ...
The Pumaman (1980)                                                             0.5
3 dev adam (Three Giant Men) (1973)                                            0.5
3 Ninjas Knuckle Up (1995)                                                     0.5
The Gracefield Incident (2015)                                                 0.5
Bloodsport: The Dark Kumite (1999)                                             0.5
Name: rating, Length: 9719, dtype: float64

In [12]:
#getting the most popular movie
popular_movie = merged_df['title'].value_counts()
print(popular_movie)

title
Forrest Gump (1994)                          329
Shawshank Redemption, The (1994)             317
Pulp Fiction (1994)                          307
Silence of the Lambs, The (1991)             279
Matrix, The (1999)                           278
                                            ...
Black Butler: Book of the Atlantic (2017)      1
No Game No Life: Zero (2017)                   1
Flint (2017)                                   1
Bungo Stray Dogs: Dead Apple (2018)            1
Andrew Dice Clay: Dice Rules (1991)            1
Name: count, Length: 9719, dtype: int64

In [17]:
#get average rating by genre
genre_ratings = merged_df.groupby("genres")["rating"].mean()
print(genre_ratings)

genres
(no genres listed)                     3.489362
Action                                 2.935484
Action|Adventure                       3.706306
Action|Adventure|Animation             3.583333
Action|Adventure|Animation|Children    3.410256
                                         ...
Sci-Fi|Thriller                        3.280172
Sci-Fi|Thriller|IMAX                   3.708333
Thriller                               3.426752
War                                    3.555556
Western                                3.658940
Name: rating, Length: 951, dtype: float64

In [19]:
# getting ratings by most active users
active_users = merged_df.groupby("userId").value_counts()
print(active_users)

userId  movieId  title                                                                                          genres                                    rating  timestamp
1       2099     Song of the South (1946)                                                                       Adventure|Animation|Children|Musical      4.0     964982588     1
        553      Tombstone (1993)                                                                               Action|Drama|Western                      5.0     964984153     1
        2005     Goonies, The (1985)                                                                            Action|Adventure|Children|Comedy|Fantasy  5.0     964981710     1
        1377     Batman Returns (1992)                                                                          Action|Crime                              3.0     964982653     1
        3729     Shaft (1971)                                                                                   Action|Crime|Drama|Thriller               5.0     964982363     1
                                                                                                                                                                               ..
610     55232    Resident Evil: Extinction (2007)                                                               Action|Horror|Sci-Fi|Thriller             2.5     1493846256    1
        8526     Around the World in 80 Days (2004)                                                             Adventure|Children|Comedy                 3.0     1479542323    1
        1429     First Strike (Police Story 4: First Strike) (Ging chaat goo si 4: Ji gaan daan yam mo) (1996)  Action|Adventure|Comedy|Thriller          3.5     1479542354    1
        3535     American Psycho (2000)                                                                         Crime|Horror|Mystery|Thriller             4.5     1493845085    1
        3564     Flintstones in Viva Rock Vegas, The (2000)                                                     Children|Comedy                           2.0     1493845744    1
Name: count, Length: 100836, dtype: int64

In [20]:
#Cleaning the datasets
#checking for missing values first, if missing, return True, if not missing, return False
print(merged_df.isnull())

        movieId  title  genres  userId  rating  timestamp
0         False  False   False   False   False      False
1         False  False   False   False   False      False
2         False  False   False   False   False      False
3         False  False   False   False   False      False
4         False  False   False   False   False      False
...         ...    ...     ...     ...     ...        ...
100831    False  False   False   False   False      False
100832    False  False   False   False   False      False
100833    False  False   False   False   False      False
100834    False  False   False   False   False      False
100835    False  False   False   False   False      False

[100836 rows x 6 columns]

In [21]:
#Let me count missing values per column
print(merged_df.isnull().sum())

movieId      0
title        0
genres       0
userId       0
rating       0
timestamp    0
dtype: int64

In [22]:
clean_df = merged_df.dropna()
clean_df

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [24]:
#Convert data types as necessary (convert timestamp to a readable datetime format).
merged_df["timestamp"] = pd.to_datetime(merged_df["timestamp"], unit="s")
merged_df

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,2000-07-30 18:45:03
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,1996-11-08 06:36:02
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,2005-01-25 06:52:26
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,2017-11-13 12:59:30
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,2011-05-18 05:28:03
...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,2018-09-16 14:44:42
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,2018-09-16 14:52:25
100833,193585,Flint (2017),Drama,184,3.5,2018-09-16 14:56:45
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,2018-09-16 15:00:21
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,2018-09-17 04:13:26

In [25]:
#Extract the release year from the title column and 
# creating a new column release_year.
merged_df["release_year"] = merged_df["title"].str.extract(r"\((\d{4})\)")
merged_df

,movieId,title,genres,userId,rating,timestamp,release_year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,2000-07-30 18:45:03,1995
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,1996-11-08 06:36:02,1995
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,2005-01-25 06:52:26,1995
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,2017-11-13 12:59:30,1995
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,2011-05-18 05:28:03,1995
...,...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,2018-09-16 14:44:42,2017
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,2018-09-16 14:52:25,2017
100833,193585,Flint (2017),Drama,184,3.5,2018-09-16 14:56:45,2017
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,2018-09-16 15:00:21,2018
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,2018-09-17 04:13:26,1991

In [33]:
#In pandas, we use vectorization operations because they can be faster especially with 
#larger datasets, if we use loops, they can be slow as i will demonstrate below;
movie_highest_rating = merged_df.groupby("title").agg(
    average_rating=("rating", "mean"),
    rating_count=("rating", "count")
)
filtered_movies = movie_highest_rating[movie_highest_rating["rating_count"] >= 100]

top_movie = filtered_movies.sort_values(
    by="average_rating",
    ascending=False
)
print("\nThe movie that has the highest average rating is: ")
print(top_movie.head(1))

The movie that has the highest average rating is:
                                  average_rating  rating_count
title
Shawshank Redemption, The (1994)        4.429022           317

In [29]:
#if we go for the 'for loop' optiono, it is so slow:
#using unique(), mean(), filtering()
movie_avg_ratings = []

for movie in merged_df["title"].unique():
    movie_data = merged_df[merged_df["title"] == movie]
    rating_count = movie_data["rating"].count()
    
    if rating_count >= 100:
        avg_rating = movie_data["rating"].mean()
        movie_avg_ratings.append((movie, avg_rating))

top_movie = sorted(movie_avg_ratings, key=lambda x: x[1], reverse=True)[0]
print("\nThe movie that has the highest average rating is: ", top_movie)
print(top_movie)

('Shawshank Redemption, The (1994)', np.float64(4.429022082018927))

In [31]:
#groupby() and agg(),this is much faster
movie_higher_rate = merged_df.groupby("title").agg(
    average_rating=("rating", "mean"),
    rating_count=("rating", "count")
)
filtered_movies = movie_higher_rate[movie_higher_rate["rating_count"] >= 100]

top_movie = filtered_movies.sort_values(
    by="average_rating",
    ascending=False
)
print("\nThe movie that has the highest average rating is: ")
print(top_movie.head(1))

The movie that has the highest average rating is:
                                  average_rating  rating_count
title
Shawshank Redemption, The (1994)        4.429022           317

In [34]:
#genre of movies tends to get the highest ratings
# Separate genres into individual rows
genres_df = merged_df.copy()
genres_df["genres"] = genres_df["genres"].str.split("|")
genres_df = genres_df.explode("genres")

# Calculate average rating and number of ratings per genre
genre_ratings = genres_df.groupby("genres").agg(
    average_rating=("rating", "mean"),
    rating_count=("rating", "count")
)

# Sort genres by highest average rating
top_genres = genre_ratings.sort_values(
    by="average_rating",
    ascending=False
)
print("\nThe genres of movies that tends to have the highest rating is: ")
print(top_genres)

The genres of movies that tends to have the highest rating is:
                    average_rating  rating_count
genres
Film-Noir                 3.920115           870
War                       3.808294          4859
Documentary               3.797785          1219
Crime                     3.658294         16681
Drama                     3.656184         41928
Mystery                   3.632460          7674
Animation                 3.629937          6988
IMAX                      3.618335          4145
Western                   3.583938          1930
Musical                   3.563678          4138
Adventure                 3.508609         24161
Romance                   3.506511         18124
Thriller                  3.493706         26452
Fantasy                   3.491001         11834
(no genres listed)        3.489362            47
Sci-Fi                    3.455721         17243
Action                    3.447984         30635
Children                  3.412956          9208
Comedy                    3.384721         39053
Horror                    3.258195          7291

In [37]:
#What is the average rating for movies released each year? 
#Option 1: use unique(), and mean().
year_results = []
for year in merged_df["release_year"].unique():
    year_data = merged_df[merged_df["release_year"] == year]
    avg_rating = year_data["rating"].mean()
    year_results.append((year, avg_rating))

year_ratings_option1 = pd.DataFrame(
    year_results,
    columns=["release_year", "average_rating"]
)
year_ratings_option1 = year_ratings_option1.sort_values(
    by="average_rating",
    ascending=False
)
print(year_ratings_option1)

   release_year  average_rating
88         1917        4.500000
70         1930        4.205882
77         1921        4.100000
33         1934        4.088235
34         1944        4.043478
..          ...             ...
50         1932        3.333333
93         1903        2.500000
84         1915        2.000000
76         1919        2.000000
92          NaN             NaN

[107 rows x 2 columns]

In [38]:
#Option 2: use groupby() and agg().
year_ratings_option2 = merged_df.groupby("release_year").agg(
    average_rating=("rating", "mean")
)
year_ratings_option2 = year_ratings_option2.sort_values(
    by="average_rating", 
    ascending=False
)
print(year_ratings_option2)

              average_rating
release_year
1917                4.500000
1930                4.205882
1921                4.100000
1934                4.088235
1944                4.043478
...                      ...
1996                3.335329
1932                3.333333
1903                2.500000
1915                2.000000
1919                2.000000

[106 rows x 1 columns]

In [40]:
print(merged_df["release_year"].dtype)
print(merged_df["release_year"].isnull().sum())

str
18

In [44]:
#Apply Custom Functions:
#Use the apply() function with a lambda to create a new column 
#that categorizes movies as "Old" if they were released before 2000, and "New" otherwise.
merged_df["movie_category"] = merged_df["release_year"].apply(
    lambda x: "Unknown" if pd.isna(x)
    else "Old" if int(x) < 2000
    else "New"
)
merged_df

,movieId,title,genres,userId,rating,timestamp,release_year,movie_category
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,2000-07-30 18:45:03,1995,Old
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,1996-11-08 06:36:02,1995,Old
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,2005-01-25 06:52:26,1995,Old
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,2017-11-13 12:59:30,1995,Old
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,2011-05-18 05:28:03,1995,Old
...,...,...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,2018-09-16 14:44:42,2017,New
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,2018-09-16 14:52:25,2017,New
100833,193585,Flint (2017),Drama,184,3.5,2018-09-16 14:56:45,2017,New
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,2018-09-16 15:00:21,2018,New
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,2018-09-17 04:13:26,1991,Old

In [45]:
#Use map() to apply this mapping to the genres column.
merged_df["main_genre"] = merged_df["genres"].str.split("|").str[0]

genre_map = {
    "Comedy": "Popular",
    "Drama": "Classic",
    "Action": "Exciting"
}

merged_df["genre_label"] = merged_df["main_genre"].map(genre_map)

merged_df[["main_genre", "genre_label"]]

       main_genre genre_label
0       Adventure         NaN
1       Adventure         NaN
2       Adventure         NaN
3       Adventure         NaN
4       Adventure         NaN
...           ...         ...
100831     Action    Exciting
100832  Animation         NaN
100833      Drama     Classic
100834     Action    Exciting
100835     Comedy     Popular

[100836 rows x 2 columns]

In [47]:
#genre_map = {
    #"Comedy": "Popular",
    #"Drama": "Classic",
    #"Action": "Exciting"
#}
#merged_df["genre_label"] = merged_df["genres"].map(genre_map)

#merged_df[["genres", "genre_label"]]