In [17]:
import pandas as pd
import numpy as np

# Step 1: Load the datasets
movies_df = pd.read_csv('movies 2.csv')
ratings_df = pd.read_excel('ratings.xlsx')
#ratings_df
movies_df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [3]:
ratings_df

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [18]:
#inspect data first
print(movies_df.isnull().sum())

#checking datatype and basic information
print(ratings_df.info())

movieId    0
title      0
genres     0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB
None

In [19]:
#inner join
inner_join = pd.merge(movies_df,ratings_df, on="movieId",
    how="inner"
)
inner_join

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [20]:
#left join
left_join = pd.merge(movies_df, ratings_df, on="movieId", 
how="left")
left_join

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,1.106636e+09
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,1.510578e+09
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,1.305696e+09
...,...,...,...,...,...,...
100849,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184.0,4.0,1.537109e+09
100850,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184.0,3.5,1.537110e+09
100851,193585,Flint (2017),Drama,184.0,3.5,1.537110e+09
100852,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184.0,3.5,1.537110e+09
100853,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331.0,4.0,1.537158e+09

In [21]:
#outer join
outer_join = pd.merge(movies_df, ratings_df, on="movieId", 
how="outer")
outer_join

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,1.106636e+09
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,1.510578e+09
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,1.305696e+09
...,...,...,...,...,...,...
100849,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184.0,4.0,1.537109e+09
100850,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184.0,3.5,1.537110e+09
100851,193585,Flint (2017),Drama,184.0,3.5,1.537110e+09
100852,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184.0,3.5,1.537110e+09
100853,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331.0,4.0,1.537158e+09

In [22]:
#right join
right_join = pd.merge(movies_df, ratings_df,on="movieId",
    how="right"
)
right_join

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,3,Grumpier Old Men (1995),Comedy|Romance,1,4.0,964981247
2,6,Heat (1995),Action|Crime|Thriller,1,4.0,964982224
3,47,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1,5.0,964983815
4,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1,5.0,964982931
...,...,...,...,...,...,...
100831,166534,Split (2017),Drama|Horror|Thriller,610,4.0,1493848402
100832,168248,John Wick: Chapter Two (2017),Action|Crime|Thriller,610,5.0,1493850091
100833,168250,Get Out (2017),Horror,610,5.0,1494273047
100834,168252,Logan (2017),Action|Sci-Fi,610,5.0,1493846352
100835,170875,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,610,3.0,1493846415

In [23]:
# Create bins
bins = [1, 2, 3, 4, 5]
# Assign ratings to bins
ratings_df["digitized_rating"] = np.digitize(
    ratings_df["rating"],
    bins
)
ratings_df

        userId  movieId  rating   timestamp  digitized_rating
0            1        1     4.0   964982703                 4
1            1        3     4.0   964981247                 4
2            1        6     4.0   964982224                 4
3            1       47     5.0   964983815                 5
4            1       50     5.0   964982931                 5
...        ...      ...     ...         ...               ...
100831     610   166534     4.0  1493848402                 4
100832     610   168248     5.0  1493850091                 5
100833     610   168250     5.0  1494273047                 5
100834     610   168252     5.0  1493846352                 5
100835     610   170875     3.0  1493846415                 3

[100836 rows x 5 columns]

In [24]:
ratings_df["rating_category"] = pd.cut(
   ratings_df["rating"],
    bins=[0, 2, 3.5, 4.5, 5],
    labels=["Low", "Medium", "High", "Very High"]
)
ratings_df

        userId  movieId  rating   timestamp  digitized_rating rating_category
0            1        1     4.0   964982703                 4            High
1            1        3     4.0   964981247                 4            High
2            1        6     4.0   964982224                 4            High
3            1       47     5.0   964983815                 5       Very High
4            1       50     5.0   964982931                 5       Very High
...        ...      ...     ...         ...               ...             ...
100831     610   166534     4.0  1493848402                 4            High
100832     610   168248     5.0  1493850091                 5       Very High
100833     610   168250     5.0  1494273047                 5       Very High
100834     610   168252     5.0  1493846352                 5       Very High
100835     610   170875     3.0  1493846415                 3          Medium

[100836 rows x 6 columns]

In [25]:
ratings_df["rating_quantile"] = pd.qcut(
   ratings_df["rating"],
    q=4,
    labels=["Q1", "Q2", "Q3", "Q4"]
)
ratings_df

,userId,movieId,rating,timestamp,digitized_rating,rating_category,rating_quantile
0,1,1,4.0,964982703,4,High,Q3
1,1,3,4.0,964981247,4,High,Q3
2,1,6,4.0,964982224,4,High,Q3
3,1,47,5.0,964983815,5,Very High,Q4
4,1,50,5.0,964982931,5,Very High,Q4
...,...,...,...,...,...,...,...
100831,610,166534,4.0,1493848402,4,High,Q3
100832,610,168248,5.0,1493850091,5,Very High,Q4
100833,610,168250,5.0,1494273047,5,Very High,Q4
100834,610,168252,5.0,1493846352,5,Very High,Q4
100835,610,170875,3.0,1493846415,3,Medium,Q1

In [26]:
ratings_df = ratings_df.fillna(0)
ratings_df

,userId,movieId,rating,timestamp,digitized_rating,rating_category,rating_quantile
0,1,1,4.0,964982703,4,High,Q3
1,1,3,4.0,964981247,4,High,Q3
2,1,6,4.0,964982224,4,High,Q3
3,1,47,5.0,964983815,5,Very High,Q4
4,1,50,5.0,964982931,5,Very High,Q4
...,...,...,...,...,...,...,...
100831,610,166534,4.0,1493848402,4,High,Q3
100832,610,168248,5.0,1493850091,5,Very High,Q4
100833,610,168250,5.0,1494273047,5,Very High,Q4
100834,610,168252,5.0,1493846352,5,Very High,Q4
100835,610,170875,3.0,1493846415,3,Medium,Q1

In [28]:
ratings_df['rating'] = ratings_df['rating'].fillna(
    ratings_df['rating'].mean())
ratings_df

,userId,movieId,rating,timestamp,digitized_rating,rating_category,rating_quantile
0,1,1,4.0,964982703,4,High,Q3
1,1,3,4.0,964981247,4,High,Q3
2,1,6,4.0,964982224,4,High,Q3
3,1,47,5.0,964983815,5,Very High,Q4
4,1,50,5.0,964982931,5,Very High,Q4
...,...,...,...,...,...,...,...
100831,610,166534,4.0,1493848402,4,High,Q3
100832,610,168248,5.0,1493850091,5,Very High,Q4
100833,610,168250,5.0,1494273047,5,Very High,Q4
100834,610,168252,5.0,1493846352,5,Very High,Q4
100835,610,170875,3.0,1493846415,3,Medium,Q1

In [29]:
ratings_df.isnull().sum()

userId              0
movieId             0
rating              0
timestamp           0
digitized_rating    0
rating_category     0
rating_quantile     0
dtype: int64

In [30]:
#stack and unstack
#we first create a pivot
ratings_wide = ratings_df.pivot(index="userId", columns="movieId",
    values="rating"
)
ratings_wide

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,2.5,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
stacked_df = ratings_wide.stack()
stacked_df

userId  movieId
1       1          4.0
        2          NaN
        3          4.0
        4          NaN
        5          NaN
                  ...
610     193581     NaN
        193583     NaN
        193585     NaN
        193587     NaN
        193609     NaN
Length: 5931640, dtype: float64

In [32]:
unstacked_df = stacked_df.unstack()
unstacked_df

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,2.5,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
#Finding most rated genres
#Will first merge the two dfs
merged_df = pd.merge(movies_df, ratings_df, on="movieId")
merged_df

,movieId,title,genres,userId,rating,timestamp,digitized_rating,rating_category,rating_quantile
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703,4,High,Q3
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962,4,High,Q3
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946,4,High,Q4
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970,2,Medium,Q1
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483,4,High,Q4
...,...,...,...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082,4,High,Q3
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545,3,Medium,Q2
100833,193585,Flint (2017),Drama,184,3.5,1537109805,3,Medium,Q2
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021,3,Medium,Q2
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606,4,High,Q3

In [35]:
#split genres into lists
merged_df["genres"] = merged_df["genres"].str.split("|")
merged_df

,movieId,title,genres,userId,rating,timestamp,digitized_rating,rating_category,rating_quantile
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]",1,4.0,964982703,4,High,Q3
1,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]",5,4.0,847434962,4,High,Q3
2,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]",7,4.5,1106635946,4,High,Q4
3,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]",15,2.5,1510577970,2,Medium,Q1
4,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]",17,4.5,1305696483,4,High,Q4
...,...,...,...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",184,4.0,1537109082,4,High,Q3
100832,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",184,3.5,1537109545,3,Medium,Q2
100833,193585,Flint (2017),[Drama],184,3.5,1537109805,3,Medium,Q2
100834,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",184,3.5,1537110021,3,Medium,Q2
100835,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],331,4.0,1537157606,4,High,Q3

In [36]:
#Exploding genres into rows
exploded_df = merged_df.explode("genres")
exploded_df

,movieId,title,genres,userId,rating,timestamp,digitized_rating,rating_category,rating_quantile
0,1,Toy Story (1995),Adventure,1,4.0,964982703,4,High,Q3
0,1,Toy Story (1995),Animation,1,4.0,964982703,4,High,Q3
0,1,Toy Story (1995),Children,1,4.0,964982703,4,High,Q3
0,1,Toy Story (1995),Comedy,1,4.0,964982703,4,High,Q3
0,1,Toy Story (1995),Fantasy,1,4.0,964982703,4,High,Q3
...,...,...,...,...,...,...,...,...,...
100832,193583,No Game No Life: Zero (2017),Fantasy,184,3.5,1537109545,3,Medium,Q2
100833,193585,Flint (2017),Drama,184,3.5,1537109805,3,Medium,Q2
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action,184,3.5,1537110021,3,Medium,Q2
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Animation,184,3.5,1537110021,3,Medium,Q2
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606,4,High,Q3

In [40]:
#Finding genre with highest number of ratings
genre_ratings = exploded_df.groupby("genres")["rating"].count()
genre_ratings.sort_values(ascending=False)

genres
Drama                 41928
Comedy                39053
Action                30635
Thriller              26452
Adventure             24161
Romance               18124
Sci-Fi                17243
Crime                 16681
Fantasy               11834
Children               9208
Mystery                7674
Horror                 7291
Animation              6988
War                    4859
IMAX                   4145
Musical                4138
Western                1930
Documentary            1219
Film-Noir               870
(no genres listed)       47
Name: rating, dtype: int64

In [39]:
#Top genre
top_genre = genre_ratings.idxmax()
top_genre

'Drama'